Use system-supplied verilog files
sifferman/calculator pull request #3
Opened 2023-11-07 21:46 UTC by aWZHY0yQH81uOYvH

May no longer need the yosys submodule

2023-11-28 17:41 UTC, sifferman commented
Waiting for https://github.com/chipsalliance/synlig/pull/2166

2023-11-28 20:43 UTC, aWZHY0yQH81uOYvH commented
And need to remove 558959e

2023-11-28 23:23 UTC, sifferman commented
Maybe waiting on https://github.com/verilator/verilator/issues/4722

2023-12-20 13:41 UTC, aWZHY0yQH81uOYvH commented
Now works with sv2v

2023-12-21 00:53 UTC, sifferman commented
The following should be added to dv/lint.vlt

```
lint_off -file "simcells.v"
lint_off -file "simlib.v"
lint_off -file "xilinx/cells_sim.v"
```

However this line should stay in case more third party Verilog is added

https://github.com/sifferman/calculator/blob/51b68ca8e9aa799a9bac03c26ca0c40e46046f6b/dv/lint.vlt#L2

2023-12-21 03:19 UTC, sifferman commented
Also, could you check if simcells.v is even needed? I think including simlib.v might be good enough

2023-12-21 03:26 UTC, aWZHY0yQH81uOYvH commented
Looks like it works without

2023-12-21 03:27 UTC, sifferman commented
Sick, I'll merge if you resolve the remaining errors :)

2023-12-21 03:32 UTC, aWZHY0yQH81uOYvH commented
Which errors? The [workflow](https://github.com/aWZHY0yQH81uOYvH/calculator/actions/runs/7283642205/job/19847806317) succeeds on GitHub and the tests pass on my computer.

2023-12-21 03:35 UTC, sifferman commented
I left some comments on the code about renaming `${INCLUDE}` to `-I${YOSYS_DATDIR}`

2023-12-21 03:37 UTC, aWZHY0yQH81uOYvH commented
I don't see them (does your code review comment still say "pending"?). I can change that anyways

2023-12-21 03:38 UTC, sifferman requested changes

2023-12-21 03:38 UTC, sifferman commented on Makefile
> +INCLUDE := -I$(shell yosys-config --datdir)
```suggestion
YOSYS_DATDIR := $(shell yosys-config --datdir)
```
I wanted to keep generic include paths inside the .f files. I don't want to create confusion that all include paths belong in the Makefile. This is simply a exception

2023-12-21 03:38 UTC, sifferman commented on Makefile
> +	verilator ${INCLUDE} -f rtl/rtl.f --lint-only --top calculator
```suggestion
	verilator -f rtl/rtl.f --lint-only --top calculator
```
Not needed

2023-12-21 03:38 UTC, sifferman commented on Makefile
> +	verilator ${INCLUDE} --Mdir $@_dir -f rtl/rtl.f -f dv/dv.f --binary --top ${TOP}
```suggestion
	verilator --Mdir $@_dir -f rtl/rtl.f -f dv/dv.f --binary --top ${TOP}
```
Not needed

2023-12-21 03:38 UTC, sifferman commented on Makefile
> +	verilator ${INCLUDE} --Mdir $@_dir -f synth/gls.f -f dv/dv.f --binary --top ${TOP}
```suggestion
	verilator -I${YOSYS_DATDIR} --Mdir $@_dir -f synth/gls.f -f dv/dv.f --binary --top ${TOP}
```

2023-12-21 03:38 UTC, sifferman commented on Makefile
> +	verilator ${INCLUDE} --Mdir $@_dir -f synth/nexys_4_ddr/nexys_4_ddr.f -f dv/dv.f --binary --top nexys_4_ddr_tb
```suggestion
	verilator -I${YOSYS_DATDIR} --Mdir $@_dir -f synth/nexys_4_ddr/nexys_4_ddr.f -f dv/dv.f --binary --top nexys_4_ddr_tb
```

2023-12-21 03:38 UTC, sifferman commented
Lol nice

2023-12-21 17:32 UTC, sifferman approved these changes

2023-12-21 17:33 UTC, merged